name: Deploy MERN App to Local Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for project
        run: |
          cd .
          npm install

      - name: Install dependencies for Frontend
        run: |
          cd client
          npm install react-scripts --save
          npm install
      
      - name: Install dependencies for Backend
        run: |
          cd server
          npm install

      - name: Build Frontend
        run: |
          cd client
          npm run build

      - name: Start Backend Server
        run: |
          cd server
          nohup npm start &

      - name: Start Frontend Server
        run: |
          cd .
          nohup serve -s build &
      
      - name: Cleanup and Finish
        run: echo "Deployment completed successfully."
